format = """
[î‚¶](fg:#7aa2f7)\
$os\
[î‚° ](fg:#7aa2f7 bg:#1a1b26)\
$directory\
$git_branch\
[î‚°](fg:#1a1b26)\
$fill\
[î‚²](fg:#1a1b26)\
$terraform\
[î‚²](fg:#212736 bg:#1d2230)\
$time\
[î‚´](fg:#1d2230)\
\n$character\
"""


[os]
format = "[$symbol]($style)"
style = 'fg:#1a1b26 bg:#7aa2f7'
disabled = false

[os.symbols]
Macos = " ï…¹ " # nf-fa-apple
Ubuntu = " ïŒ› " # nf-linux-ubuntu
Debian = " ïŒ† " # nf-linux-debian
NixOS = "ğŸ§" #nf-linux-nixos 

[directory]
truncation_length = 5
truncation_symbol = 'ï¼ ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = 'î˜— ~' # nf-costum-home
style = 'fg:#7aa2f7 bg:#1a1b26'
read_only = ' ó°Œ¾ ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = 'ï„¦' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 12
truncation_symbol = ''
style = 'fg:bold #A4A4A4 bg:#1a1b26'
format = '[ î‚± $symbol $branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[fill]
symbol = ' '
style = 'black'

[character]
success_symbol = '[â¯](bold #9ece6a)'
error_symbol = '[â¯](bold red)'

[terraform]
symbol = 'ğŸ’ '
format = '[ $symbol ($version) ]($style)'
style = 'fg:bold #8000FF bg:#1a1b26'

[time]
disabled = false
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'
time_format = '%T'
utc_time_offset = '+9'
